/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeakingRouteImport } from './routes/speaking'
import { Route as RiseCollectiveRouteImport } from './routes/rise-collective'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AcceleratorRouteImport } from './routes/accelerator'
import { Route as IndexRouteImport } from './routes/index'

const SpeakingRoute = SpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => rootRouteImport,
} as any)
const RiseCollectiveRoute = RiseCollectiveRouteImport.update({
  id: '/rise-collective',
  path: '/rise-collective',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceleratorRoute = AcceleratorRouteImport.update({
  id: '/accelerator',
  path: '/accelerator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accelerator': typeof AcceleratorRoute
  '/apply': typeof ApplyRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/rise-collective': typeof RiseCollectiveRoute
  '/speaking': typeof SpeakingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accelerator': typeof AcceleratorRoute
  '/apply': typeof ApplyRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/rise-collective': typeof RiseCollectiveRoute
  '/speaking': typeof SpeakingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accelerator': typeof AcceleratorRoute
  '/apply': typeof ApplyRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/rise-collective': typeof RiseCollectiveRoute
  '/speaking': typeof SpeakingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accelerator'
    | '/apply'
    | '/blog'
    | '/book'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/rise-collective'
    | '/speaking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accelerator'
    | '/apply'
    | '/blog'
    | '/book'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/rise-collective'
    | '/speaking'
  id:
    | '__root__'
    | '/'
    | '/accelerator'
    | '/apply'
    | '/blog'
    | '/book'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/rise-collective'
    | '/speaking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceleratorRoute: typeof AcceleratorRoute
  ApplyRoute: typeof ApplyRoute
  BlogRoute: typeof BlogRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  RiseCollectiveRoute: typeof RiseCollectiveRoute
  SpeakingRoute: typeof SpeakingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/speaking': {
      id: '/speaking'
      path: '/speaking'
      fullPath: '/speaking'
      preLoaderRoute: typeof SpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rise-collective': {
      id: '/rise-collective'
      path: '/rise-collective'
      fullPath: '/rise-collective'
      preLoaderRoute: typeof RiseCollectiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accelerator': {
      id: '/accelerator'
      path: '/accelerator'
      fullPath: '/accelerator'
      preLoaderRoute: typeof AcceleratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceleratorRoute: AcceleratorRoute,
  ApplyRoute: ApplyRoute,
  BlogRoute: BlogRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  RiseCollectiveRoute: RiseCollectiveRoute,
  SpeakingRoute: SpeakingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
